# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: lemons_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface

hardware_interface:
  joints:
    - rotation1
    - rotation2
    - prismatic1
    - left_gripper_finger_joint
    - right_gripper_finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity

# Publish all joint states
# Creates the /joint_states topic necessary in ROS

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    name: "joint_state_controller"
    action_ns: ""

# gazebo_ros_control:
#
#     pid_gains:
#
#         rotation1:
#             p: 100.0
#             i: 0.01
#             d: 10.0
#
#         rotation2:
#             p: 100.0
#             i: 0.01
#             d: 10.0
#
#         prismatic1:
#             p: 100.0
#             i: 0.01
#             d: 10.0

arm_position_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - rotation1
        - rotation2
        - prismatic1
    gains:
        rotation1:
            p: 100
            d: 10.0
            i: 0.01
            i_clamp: 1

        rotation2:
            p: 100.0
            d: 10.0
            i: 0.01
            i_clamp: 1

        prismatic1:
            p: 100.0
            i: 0.01
            d: 10.0
            i_clamp: 1

    constraints:
        goal_time: 2.0

controller_list:

    - name: arm_position_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
          - rotation1
          - rotation2
          - prismatic1


